''' CDD '''
dataset_cdd = r'/root/zyn/Datasets/CDD'
train_root = dataset_cdd + '/train'
train_src_t1 = train_root + '/A'
train_src_t2 = train_root + '/B'
train_label = train_root + '/OUT'

val_root = dataset_cdd + '/val'
val_src_t1 = val_root + '/A'
val_src_t2 = val_root + '/B'
val_label = val_root + '/OUT'

test_root = dataset_cdd + '/test'
test_src_t1 = test_root + '/A'
test_src_t2 = test_root + '/B'
test_label = test_root + '/OUT'
test_predict = test_root + '/predict'
